### PR TITLE
Feature/seab 6017/update avro

### PR DESCRIPTION
**Pull request by denis-yuen**
Updates to newer avro, which needed newer python, which meant newer setup tools and importlib-resources, and on and on. 

https://ucsc-cgl.atlassian.net/browse/SEAB-6017

### CODE REVIEW

**Comment by denis-yuen** [comment]
Note to self: something about the deserialization of default values is broken as early as 1.10.2
(possibly earlier, but some of our sed customizations for 1.11.3 are problematic)

**Comment by denis-yuen** [comment]
Hmmm, cwltool also broken in some way by python update(?) but not locally

**Comment by denis-yuen** [comment]
Last three failures could have something to do with https://issues.apache.org/jira/browse/AVRO-1592 although that seems to be before 1.8.1

**Comment by denis-yuen** [comment]
Note to self: if re-triggering tests pass, then this is ready for release and testing with dockstore-webservice
If only artifacts.oicr.on.ca was up

**Review by coverbeck — APPROVED** [review]
I skipped over reviewing all the Java files in cwlavro-generated because I assume, based on the directory name, that they are... generated. If that's not the case, please re-request review and I'll go over them.

**Comment by denis-yuen** [comment]
@coverbeck  Yeah, I should have commented. The important bits are the build and the pom files.
The rest can be ignored/skimmed

**Review by kathy-t — APPROVED** [review]
Thanks for taking over this ticket!

**Pull request merged**
